#! /bin/sh
#
# examples of Julia sets
#
# (c) 2014 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
for platform in 0
do
	sizeparams="-w 2560 -h 1440 -x -2 -y -1.125 -W 4 -H 2.25"
	for v in 2 ""
	do
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u -0.1  -v 0.1  out${v}-${platform}-a.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u -0.5  -v 0.5  out${v}-${platform}-b.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u -1    -v 0.05 out${v}-${platform}-c.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u -0.1  -v 0.75 out${v}-${platform}-d.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u  0.25 -v 0.52 out${v}-${platform}-e.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u -0.5  -v 0.55 out${v}-${platform}-f.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u  0    -v 0.66 out${v}-${platform}-g.fits
		time ./julia${v} ${sizeparams} -P ${plattform} \
				-u  0    -v 1    out${v}-${platform}-h.fits
	done
done
