#! /bin/sh
#
# examples of Julia sets
#
# (c) 2014 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
for platform in 0 1 2
do
	for v in 0 1 2
	do
		for example in a b c d e f g h
		do
			case ${example} in
				a)	point="'(-0.1,0.1)'"
					;;
				b)	point="'(-0.5,0.5)'"
					;;
				c)	point="'(-1,0.05)'"
					;;
				d)	point="'(-0.1,0.75)'"
					;;
				e)	point="'(0.25,0.52)'"
					;;
				f)	point="'(-0.5,0.55)'"
					;;
				g)	point="'(0,0.66)'"
					;;
				h)	point="'(0,1)'"
					;;
			esac
			commonparams="-d -w 2560 -h 1440 -o '(-2.1,-1.18125)' -S '(4.1,2.3625)' -c ${point}"
			outfile=out${v}-P${platform}-${example}.fits
			histofile=histo${v}-P${platform}-${example}.csv
			case ${v} in
				0)	time ./julia1 ${commonparams} -e ${outfile}
					;;
				1)	time ./julia1 ${commonparams} -C ${outfile}
					;;
				2)	time ./julia2 ${commonparams} -s -H ${histofile} ${outfile}
					;;
			esac
		done
	done
done

for x in a b c d e f g h
do
	convert out0-P0-${x}.fits -gamma 1.5 ${x}.png
	convert out2-P0-${x}.fits -negate j-${x}.png
done
