#
# Makefile -- Bilder fuer den Artikel ueber die Waermeleitungsgleichung
#
# (c) 2014 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
heat-1.pdf heat-2.pdf:	heat.mp
	TEX=latex mpost heat.mp
	mptopdf heat.1
	mptopdf heat.2
