#! /bin/sh
#
# create video from the fits files found in the images directory
#
# (c) 2014 Prof Dr Anreas Mueller, Hochschule Rapperswil
#
for f in images/*.fits
do
	jpgname=images/`basename $f .fits`.jpg
	if [ ! -r ${jpgname} ]
	then
		convert $f -resize 50% ${jpgname}
	fi
done

jpeg2yuv -v 1 -I p -f 25 -j images/%05d.jpg | \
	mpeg2enc --no-constraints -q 1 -b 8000 -l m -f 8 -o potential.mpg
