#!/bin/sh
#
# Bilder zusammenkopieren aus zwei verschiedenen Ordner
# anschliessen ausführen des Skriptes combine
convert -size 256x128 xc:black canvas.jpg
for f in {00000..00256}
do
		bash combine west/$f.fits east/$f.fits $f.jpg 
done

jpeg2yuv -v 1 -I p -f 25 -j %05d.jpg | \
	mpeg2enc --no-constraints -q 1 -b 8000 -l m -f 8 -o potential_combine.mpg
